import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/views/public.theme";
import { PlusJakartaSans } from "@/lib/plus-jakarta-sans.font";
import "./globals.css";
import AuthProvider from "@/views/contexts/AuthContext";
import { getAuth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Jasa di Riau",
  description: "Generated by create next app",
};

export default async function RootLayout({
  header,
  children,
  footer,
}: Readonly<{
  header: React.ReactNode;
  children: React.ReactNode;
  footer: React.ReactNode;
}>) {
  const auth = await getAuth();
  return (
    <html lang="en" className={PlusJakartaSans.variable}>
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body className="main-body">
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <AuthProvider initialState={auth}>
              {header}
              {children}
              {footer}
            </AuthProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
