import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/views/public.theme";
import { PlusJakartaSans } from "@/lib/plus-jakarta-sans.font";
import Toolbar from "@mui/material/Toolbar";
import "./globals.css";
import Box from "@mui/material/Box";

export const metadata: Metadata = {
  title: "Jasa di Riau",
  description: "Generated by create next app",
};

export default function RootLayout({
  header,
  children,
  footer,
}: Readonly<{
  header: React.ReactNode;
  children: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en" className={PlusJakartaSans.variable}>
      <body className="main-body">
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            {header}

            {children}
            {footer}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
