name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_dummy
        options: >-
          --health-cmd="pg_isready -U postgres -d db_dummy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # Pakai dummy DB supaya prisma/next build nggak error
      DATABASE_URL: postgresql://postgres:postgres@localhost:5433/db_dummy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Next.js
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t image-jasadiriau:latest .

      - name: Save Docker image as tar
        run: docker save image-jasadiriau:latest -o image-jasadiriau.tar

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "image-jasadiriau.tar"
          target: "/home/jasadiriau/deploy/"

      - name: SSH to VPS and deploy with docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY_LITERAL }}
          script: |
            cd /home/jasadiriau/deploy
            docker load -i image-jasadiriau.tar
            docker-compose down
            docker-compose up -d
            rm -f image-jasadiriau.tar
