name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build Docker image (skip DB)
      run: docker build --build-arg SKIP_DB=true -t image-jasadiriau:latest .

    - name: Save Docker image as tar
      run: docker save image-jasadiriau:latest -o image-jasadiriau.tar
      
    # - name: Tar workspace
    #   run: |
    #     cd $GITHUB_WORKSPACE
    #     tar --exclude='image-jasadiriau.tar' -czvf $GITHUB_WORKSPACE/archive.tar.gz .

    - name: List workspace
      run: ls -l #$GITHUB_WORKSPACE
      
    - name: Fix permissions for Docker image
      run: chmod 644 image-jasadiriau.tar

    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "SSH connection successful!"
          echo "Logged in user: $(whoami)"
          echo "Hostname: $(hostname)"
          uname -a

    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "image-jasadiriau.tar"
        target: "/home/jasadiriau/deploy/"

    - name: SSH to VPS and deploy with docker-compose
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/jasadiriau/deploy
          sudo docker load -i image-jasadiriau.tar
          sudo docker compose down
          sudo docker compose up -d
          rm -f image-jasadiriau.tar
