
name: Test VPS SSH

on:
  workflow_dispatch:  # Bisa trigger manual dari GitHub Actions

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 123.45.67.89
        username: jasadiriau
        password: Jasadiriau123
        script: |
          echo "SSH connection successful!"
          uname -a
