name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build Docker image (skip DB)
      run: |
        docker build \
          --build-arg SKIP_DB=true \
          --build-arg DB_USER=${{ secrets.DB_USER }} \
          --build-arg DB_PASS=${{ secrets.DB_PASS }} \
          --build-arg DB_NAME=${{ secrets.DB_NAME }} \
          --build-arg DB_HOST=172.17.0.1 \
          --build-arg DB_PORT=5432 \
          --build-arg DB_SCHEMA=public \
          --build-arg DATABASE_URL="postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@172.17.0.1:5432/${{ secrets.DB_NAME }}?schema=public" \
          --build-arg BASE_URL=https://jasadiriau.com \
          --build-arg NEXT_PUBLIC_BASE_URL=https://jasadiriau.com \
          --build-arg NEXT_PUBLIC_IMAGE_PATH=uploads/images \
          --build-arg NEXT_PUBLIC_WA_LINK=https://api.whatsapp.com/send \
          --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID="92261591557-raee5naceogcbfb1mhbddcu6nggt0685.apps.googleusercontent.com" \
          --build-arg SESSION_SECRET="mgxiOqv3UA5nlZ1w+jbBh9jN1VyzkIfDiEeRrrYWV4I=" \
          -t image-jasadiriau:latest .

    - name: Save Docker image as tar
      run: docker save image-jasadiriau:latest -o $GITHUB_WORKSPACE/image-jasadiriau.tar

    - name: List workspace
      run: ls -l $GITHUB_WORKSPACE
      
    # - name: Fix permissions for Docker image
    #   run: chmod 644 $GITHUB_WORKSPACE/image-jasadiriau.tar

    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "SSH connection successful!"
          echo "Logged in user: $(whoami)"
          echo "Hostname: $(hostname)"
          uname -a

    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "$GITHUB_WORKSPACE/image-jasadiriau.tar"
        target: "/home/jasadiriau/deploy/"

    - name: SSH to VPS and deploy with docker-compose
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/jasadiriau/deploy
          sudo docker load -i image-jasadiriau.tar
          sudo docker-compose down
          sudo docker-compose up -d
          rm -f image-jasadiriau.tar
