name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SCHEMA: public
      DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5433/${{ secrets.DB_NAME }}?schema=public

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Setup SSH tunnel to Postgres
      run: |
        ssh -o StrictHostKeyChecking=no -f -N \
          -i ~/.ssh/id_rsa \
          -L 5433:localhost:5432 \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        echo "👉 Using DATABASE_URL=$DATABASE_URL"
        docker build \
          --build-arg DATABASE_URL=$DATABASE_URL \
          -t image-jasadiriau:latest .

    - name: Save Docker image as tar
      run: docker save image-jasadiriau:latest -o image-jasadiriau.tar

    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "image-jasadiriau.tar"
        target: "/home/jasadiriau/deploy/"

    - name: SSH to VPS and run container
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/jasadiriau/deploy
          docker load -i image-jasadiriau.tar
          docker stop app_jasadiriau || true
          docker rm app_jasadiriau || true
          docker run -d \
            --name app_jasadiriau \
            -p 4000:4000 \
            -e DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5432/${{ secrets.DB_NAME }}?schema=public \
            -e BASE_URL=https://jasadiriau.com \
            -e NEXT_PUBLIC_BASE_URL=https://jasadiriau.com \
            -e NEXT_PUBLIC_IMAGE_PATH=uploads/images \
            -e NEXT_PUBLIC_WA_LINK=https://api.whatsapp.com/send \
            -e NEXT_PUBLIC_GOOGLE_CLIENT_ID="92261591557-raee5naceogcbfb1mhbddcu6nggt0685.apps.googleusercontent.com" \
            -e SESSION_SECRET="mgxiOqv3UA5nlZ1w+jbBh9jN1VyzkIfDiEeRrrYWV4I=" \
            image-jasadiriau:latest
          rm -f image-jasadiriau.tar
