name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Buat SSH tunnel ke VPS supaya bisa akses Postgres dari runner
      - name: Setup SSH tunnel to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -f -N \
            -L 5433:localhost:5432 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        env:
          DATABASE_URL: postgresql://${{ secrets.DB_USER }}:db%@localhost:5433/${{ secrets.DB_NAME }}?schema=public
        run: npx prisma generate

      - name: Build Next.js
        env:
          DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5433/${{ secrets.DB_NAME }}?schema=public
          BASE_URL: https://jasadiriau.com
          NEXT_PUBLIC_BASE_URL: https://jasadiriau.com
          NEXT_PUBLIC_IMAGE_PATH: uploads/images
          NEXT_PUBLIC_WA_LINK: https://api.whatsapp.com/send
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: "92261591557-raee5naceogcbfb1mhbddcu6nggt0685.apps.googleusercontent.com"
          SESSION_SECRET: "mgxiOqv3UA5nlZ1w+jbBh9jN1VyzkIfDiEeRrrYWV4I="
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t image-jasadiriau:latest .

      - name: Save Docker image as tar
        run: docker save image-jasadiriau:latest -o image-jasadiriau.tar

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "image-jasadiriau.tar"
          target: "/home/jasadiriau/deploy/"

      - name: SSH to VPS and deploy with docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY_LITERAL }}
          script: |
            cd /home/jasadiriau/deploy
            docker load -i image-jasadiriau.tar
            docker-compose down
            docker-compose up -d
            rm -f image-jasadiriau.tar
